/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.laboratorio_3;

import javax.swing.table.DefaultTableModel;
import Funciones.*;
import java.awt.Frame;
import java.io.FileOutputStream;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;


/**
 *
 * @author diego
 */
public class Principal extends javax.swing.JFrame {

    private TableModel modelo;
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("Laboratorio 3.0");
        Otras.colocarColumnas(jTable1);
        
        
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        path_archivo = new javax.swing.JTextField();
        eliminar_linea = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bt_refrescar = new javax.swing.JButton();
        bt_cargarSiglea = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        nueva_tabla = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        importarCsv = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        gral_comun = new javax.swing.JMenuItem();
        gral_caseina = new javax.swing.JMenuItem();
        exportarWilliner = new javax.swing.JMenuItem();
        exportarGarcia = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        exportarMilkautTambos = new javax.swing.JMenuItem();
        exportarMilkautCisternas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        exportarSiglea = new javax.swing.JMenuItem();
        exportarSigleaTildados = new javax.swing.JMenuItem();
        exportarVeronica = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        reemplazarFecha = new javax.swing.JMenuItem();
        reempOtrosCampos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        generar_informe = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jScrollPane1.setViewportView(jTable1);

        eliminar_linea.setText("Eliminar fila");
        eliminar_linea.setActionCommand("");
        eliminar_linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_lineaActionPerformed(evt);
            }
        });

        jButton1.setText("Cargar Inhibidores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bt_refrescar.setText("Refrescar");
        bt_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refrescarActionPerformed(evt);
            }
        });

        bt_cargarSiglea.setText("Cargar siglea");
        bt_cargarSiglea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cargarSigleaActionPerformed(evt);
            }
        });

        jMenu4.setText("Nuevo");

        nueva_tabla.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        nueva_tabla.setText("Nueva Tabla");
        nueva_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueva_tablaActionPerformed(evt);
            }
        });
        jMenu4.add(nueva_tabla);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Importar");

        importarCsv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        importarCsv.setText("CSV");
        importarCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarCsvActionPerformed(evt);
            }
        });
        jMenu1.add(importarCsv);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exportar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu6.setText("General");

        gral_comun.setText("Común");
        gral_comun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gral_comunActionPerformed(evt);
            }
        });
        jMenu6.add(gral_comun);

        gral_caseina.setText("Con caseína");
        gral_caseina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gral_caseinaActionPerformed(evt);
            }
        });
        jMenu6.add(gral_caseina);

        jMenu2.add(jMenu6);

        exportarWilliner.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exportarWilliner.setText("Williner");
        exportarWilliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarWillinerActionPerformed(evt);
            }
        });
        jMenu2.add(exportarWilliner);

        exportarGarcia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exportarGarcia.setText("Garcia");
        exportarGarcia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarGarciaActionPerformed(evt);
            }
        });
        jMenu2.add(exportarGarcia);

        jMenu5.setText("Milkaut");

        exportarMilkautTambos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exportarMilkautTambos.setText("Milkaut Tambo");
        exportarMilkautTambos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarMilkautTambosActionPerformed(evt);
            }
        });
        jMenu5.add(exportarMilkautTambos);

        exportarMilkautCisternas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exportarMilkautCisternas.setText("Milkaut Cisternas");
        exportarMilkautCisternas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarMilkautCisternasActionPerformed(evt);
            }
        });
        jMenu5.add(exportarMilkautCisternas);

        jMenu2.add(jMenu5);

        jMenu7.setText("Siglea");

        exportarSiglea.setText("Todo");
        exportarSiglea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarSigleaActionPerformed(evt);
            }
        });
        jMenu7.add(exportarSiglea);

        exportarSigleaTildados.setText("Señalados");
        exportarSigleaTildados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarSigleaTildadosActionPerformed(evt);
            }
        });
        jMenu7.add(exportarSigleaTildados);

        jMenu2.add(jMenu7);

        exportarVeronica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        exportarVeronica.setText("Veronica");
        exportarVeronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarVeronicaActionPerformed(evt);
            }
        });
        jMenu2.add(exportarVeronica);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reemplazar");

        reemplazarFecha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        reemplazarFecha.setText("Fecha");
        reemplazarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reemplazarFechaActionPerformed(evt);
            }
        });
        jMenu3.add(reemplazarFecha);

        reempOtrosCampos.setText("Otros Campos");
        reempOtrosCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reempOtrosCamposActionPerformed(evt);
            }
        });
        jMenu3.add(reempOtrosCampos);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Informes");

        generar_informe.setText("Generar Informe");
        generar_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_informeActionPerformed(evt);
            }
        });
        jMenu8.add(generar_informe);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Altas");
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Agregar empresa informe");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem5);

        jMenuItem6.setText("Agregar cliente");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem6);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(path_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(bt_refrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cargarSiglea, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminar_linea))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar_linea)
                    .addComponent(jButton1)
                    .addComponent(bt_refrescar)
                    .addComponent(bt_cargarSiglea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importarCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarCsvActionPerformed
        // TODO add your handling code here:

        String rutaArchivo = archivo.abrirArchivo();
        path_archivo.setText(rutaArchivo);
        switch (archivo.detectarTipoCsv(rutaArchivo)) {
            case 0:
                archivo.cargarArchivoFoss(path_archivo, jTable1);
                archivo.removerFilas(jTable1);
                //jTable1.setDefaultRenderer(Object.class, new Resaltador(6));
                //jTable1.setDefaultRenderer(Object.class, new Resaltador());
                break;
            case 1:
                archivo.cargarArchivoIbc(path_archivo, jTable1);
                archivo.removerFilas(jTable1);
                //jTable1.setDefaultRenderer(Object.class, new Resaltador(6));
                break;
            case 2:
                archivo.cargarArchivoCombi(path_archivo, jTable1);
                archivo.removerFilas(jTable1);
                //jTable1.setDefaultRenderer(Object.class, new Resaltador(6));

                break;
            case 3:
                archivo.cargarArchivoCombiConCaseina(path_archivo, jTable1);
                archivo.removerFilas(jTable1);
                //jTable1.setDefaultRenderer(Object.class, new Resaltador(6));
                break;
            default:
                JOptionPane.showMessageDialog(null, "Alerta", "Tipo no valido", JOptionPane.ERROR_MESSAGE);

        }
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setRowSelectionAllowed(true);
       
        //archivo.cargarArchivoFoss(path_archivo, jTable1);
        //archivo.removerFilas(jTable1);
        //archivo.volcarFoss(rutaArchivo, jTable1);
    }//GEN-LAST:event_importarCsvActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenu2ActionPerformed

    private void nueva_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueva_tablaActionPerformed
        // TODO add your handling code here:

        Otras.nuevo(jTable1);

    }//GEN-LAST:event_nueva_tablaActionPerformed

    private void exportarWillinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarWillinerActionPerformed
        // TODO add your handling code here:

        exFile.obtenerModelo(jTable1);
        FileWriter fw = exFile.exportarTxt();
        exFile.formatoWilliner(fw);
    }//GEN-LAST:event_exportarWillinerActionPerformed

    private void exportarGarciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarGarciaActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileWriter fw = exFile.exportarTxt();
        exFile.formatoGarcia(fw);

    }//GEN-LAST:event_exportarGarciaActionPerformed

    private void exportarMilkautCisternasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarMilkautCisternasActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileOutputStream fo = exFile.exportarTablaExcel();
        exFile.formatoMilkautCisternas(fo, jTable1);
    }//GEN-LAST:event_exportarMilkautCisternasActionPerformed

    private void exportarVeronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarVeronicaActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileOutputStream fo = exFile.exportarTablaExcel();
        exFile.formatoVeronica(fo, jTable1);
    }//GEN-LAST:event_exportarVeronicaActionPerformed

    private void exportarMilkautTambosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarMilkautTambosActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileOutputStream fo = exFile.exportarTablaExcel();
        exFile.formatoMilkautTambos(fo, jTable1);
    }//GEN-LAST:event_exportarMilkautTambosActionPerformed

    private void reemplazarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reemplazarFechaActionPerformed
        // TODO add your handling code here:
        Otras.reemplazarFecha(jTable1);
    }//GEN-LAST:event_reemplazarFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Otras.cargarInhFilasSeleccionadas(jTable1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminar_lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_lineaActionPerformed
        // TODO add your handling code here:
        Otras.eliminarFila(jTable1);
    }//GEN-LAST:event_eliminar_lineaActionPerformed

    private void bt_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refrescarActionPerformed
        // TODO add your handling code here:
        Otras.refrescar(jTable1);

    }//GEN-LAST:event_bt_refrescarActionPerformed

    private void gral_comunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gral_comunActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileOutputStream fo = exFile.exportarTablaExcel();
        exFile.formatoGral(fo, jTable1);

    }//GEN-LAST:event_gral_comunActionPerformed

    private void gral_caseinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gral_caseinaActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileOutputStream fo = exFile.exportarTablaExcel();
        exFile.formatoGralCaseina(fo, jTable1);
    }//GEN-LAST:event_gral_caseinaActionPerformed

    private void exportarSigleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarSigleaActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileOutputStream fo = exFile.exportarTablaExcel();
        exFile.formatoSiglea(fo, jTable1);
        
    }//GEN-LAST:event_exportarSigleaActionPerformed

    private void exportarSigleaTildadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarSigleaTildadosActionPerformed
        // TODO add your handling code here:
        exFile.obtenerModelo(jTable1);
        FileOutputStream fo = exFile.exportarTablaExcel();
        exFile.formatoSigleaTildados(fo, jTable1);
    }//GEN-LAST:event_exportarSigleaTildadosActionPerformed

    private void bt_cargarSigleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cargarSigleaActionPerformed
        // TODO add your handling code here:
        Otras.cargarSigleaFilasSeleccionadas(jTable1);
    }//GEN-LAST:event_bt_cargarSigleaActionPerformed

    private void generar_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_informeActionPerformed
        // TODO add your handling code here:
        this.setTabla(jTable1);
        
        Opciones opciones = null;
        opciones = new Opciones(this, true);
        
        opciones.setVisible(rootPaneCheckingEnabled);
        
        
    }//GEN-LAST:event_generar_informeActionPerformed

    private void reempOtrosCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reempOtrosCamposActionPerformed
        // TODO add your handling code here:
        Buscar_Reemplazar br = new Buscar_Reemplazar(this,true);
        br.setVisible(true);
    }//GEN-LAST:event_reempOtrosCamposActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        AltaEmpresa altemp = new AltaEmpresa(this,true);
        altemp.setLocation(300,200);
        altemp.setVisible(rootPaneCheckingEnabled);
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        AltaCliente altcli = new AltaCliente(this,true);
        altcli.setLocation(300,200);
        altcli.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public DefaultTableModel getModelo(JTable jTable1){
        return (DefaultTableModel) jTable1.getModel();
    }
    public int prueba(JTable jTable1){
        System.out.println(jTable1.getColumnName(3));
        return 8;
    }
    
    public void setModelo(DefaultTableModel modelo, JTable jTable1){
        this.modelo = jTable1.getModel();
        System.out.println(this.modelo.getRowCount());
    }
    
    public JTable getTabla(){
        return jTable1;
    }
    
    public void setTabla(JTable jTable1){
        this.jTable1 = jTable1;
    }
    
    

    Importar archivo = new Importar();
    Exportar exFile = new Exportar();
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cargarSiglea;
    private javax.swing.JButton bt_refrescar;
    private javax.swing.JButton eliminar_linea;
    private javax.swing.JMenuItem exportarGarcia;
    private javax.swing.JMenuItem exportarMilkautCisternas;
    private javax.swing.JMenuItem exportarMilkautTambos;
    private javax.swing.JMenuItem exportarSiglea;
    private javax.swing.JMenuItem exportarSigleaTildados;
    private javax.swing.JMenuItem exportarVeronica;
    private javax.swing.JMenuItem exportarWilliner;
    private javax.swing.JMenuItem generar_informe;
    private javax.swing.JMenuItem gral_caseina;
    private javax.swing.JMenuItem gral_comun;
    private javax.swing.JMenuItem importarCsv;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JMenuItem nueva_tabla;
    private javax.swing.JTextField path_archivo;
    private javax.swing.JMenuItem reempOtrosCampos;
    private javax.swing.JMenuItem reemplazarFecha;
    // End of variables declaration//GEN-END:variables
}
